all:
	g++ -O3 -ldl -pthread multithreading_test1.cpp -o multithreading_test1.o -lncurses;
debug:
	g++ -g -O3 -ldl -pthread multithreading_test1.cpp -o multithreading_test1.exe -lncurses;
clean:
	rm *.o *.exe
